name: Quality assurance

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Quality assurance

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: phpcs, phpstan
          coverage: xdebug

      - uses: actions/checkout@v4
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Build assets
        run: |
          npm install
          npm run build

      - name: phpcs
        run: vendor/bin/phpcs --standard=ruleset.xml

      - name: phpstan
        run: vendor/bin/phpstan analyse

      - name: PHPUnit tests
        run: vendor/phpunit/phpunit/phpunit --configuration phpunit.xml --coverage-clover ./coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: patrikjak/utils
          files: ./coverage.xml